const rotinaDiaria = [
    { hora: "04:00", atividade: "Acordar, tomar café e se preparar para ir trabalhar" },
    { hora: "04:20", atividade: "Sair de casa para pagar o ônibus)" },
    { hora: "05:10", atividade: "Chegar no metrô Belêm" },
    { hora: "05:30", atividade: "Chegar no trabalho" },
    { hora: "10:30", atividade: "Resolvo realizar meu almoço" },
    { hora: "11:30", atividade: "Volto da minha pausa para o segundo round do trabalho" },
    { hora: "15:30", atividade: "finalizo meu plantão" },
    { hora: "16:00", atividade: "Saio do metrô para pegar o ônibus para ir para o estágio" },
    { hora: "17:00", atividade: "A caminho do estágio" },
    { hora: "17:17", atividade: "Inicio meu estágio" },
    { hora: "21:30", atividade: "Finalizo meu estagio" },
    { hora: "22:00", atividade: "Chego em minha casa e tomo um banho" },
    { hora: "23:00", atividade: "E por fim deito para descansar" },
  ];
  console.log(rotinaDiaria)